export const PasswordRules =
  'Every password needs at least 8 characters, a capital and a lower case letter, and a number.';

export enum MessageType {
  Sent = 'Successfully sent',
  Resent = 'Successfully resent',
  Updated = 'Successfully updated',
  Created = 'Successfully created',
  Deleted = 'Successfully deleted',
  Purchased = 'Successfully purchased',
  Restored = 'Successfully restored',
  Verified = 'Successfully verified',
  Added = 'Successfully added',
  Submitted = 'Successfully submitted',
  Invited = 'Successfully invited',
  Accepted = 'Successfully accepted',
  SignOutSuccess = 'Successfully signed out',
  SignOutError = 'Failed to sign out'
}

/**
 * Every toast the app can show, named by subject and outcome.
 *
 * Shape is "<Subject> <past-tense verb>" so five near-identical trays on the
 * pet screen do not all confirm with the same sentence -- the toast is the only
 * thing that tells a member which sheet they just saved.
 */
export enum SuccessMessage {
  BioUpdated = 'Bio updated',
  CareCardUpdated = 'Care Card updated',
  FeedDeleted = 'Feed deleted',
  FeedLoggedAlertsOff = 'Feed Logged Alerts off',
  FeedLoggedAlertsOn = 'Feed Logged Alerts on',
  FeedTimeAdded = 'Feed time added',
  FeedTimeRemoved = 'Feed time removed',
  FeedsPaused = 'Feeds paused',
  FeedsResumed = 'Feeds resumed',
  FeedTimeUpdated = 'Feed time updated',
  FeedUpdated = 'Feed updated',
  GraceWindowUpdated = 'Feed timing updated',
  HouseholdJoined = 'Household joined',
  HouseholdLeft = 'You left the household',
  InviteRevoked = 'Invite revoked',
  InviteSent = 'Invite sent',
  HouseholdRenamed = 'Household renamed',
  MemberRemoved = 'Member removed',
  MemberRoleChanged = 'Role updated',
  ContactAdded = 'Contact added',
  ContactUpdated = 'Contact updated',
  ContactRemoved = 'Contact removed',
  MedicationAdded = 'Medication added',
  MedicationRemoved = 'Medication removed',
  MedicationUpdated = 'Medication updated',
  NameSaved = 'Name saved',
  ProfilePhotoUpdated = 'Profile photo updated',
  OnboardingCompleted = 'Pet profile completed',
  PetAdded = 'Pet added',
  PetDetailsUpdated = 'Pet details updated',
  PetPhotoUpdated = 'Photo updated',
  PetRemoved = 'Pet removed',
  PhotoAdded = 'Photo added',
  PhotoDeleted = 'Photo deleted',
  PhotosAdded = 'Photos added',
  PostDeleted = 'Post deleted',
  PostShared = 'Post shared',
  PostUpdated = 'Post updated',
  PasswordUpdated = 'Password updated',
  ResetCodeSent = 'If that address has an account, we have sent a code',
  CodeResent = 'New code sent',
  SignedIn = 'Signed in',
  SignedOut = 'Signed out',
  TimezoneUpdated = 'Timezone updated'
}

/**
 * Failures the user can do something about. Never carries a raw Postgres or
 * Supabase string -- those are written for developers.
 */
export enum ErrorMessage {
  AlertsMarkReadFailed = 'Could not mark notifications as read',
  BioUpdateFailed = 'Could not update bio',
  CameraAccessDenied = 'Allow camera access in Settings to take a photo',
  CareCardShareFailed = 'Could not make the Care Card PDF',
  CareCardShareUnavailable = 'This device has nowhere to share the PDF to',
  CareCardUpdateFailed = 'Could not update the Care Card',
  FeedTimeRemoveFailed = 'Could not remove the feed time',
  FeedTimeSaveFailed = 'Could not save the feed time',
  FeedsPauseFailed = 'Could not pause feeds',
  FeedsResumeFailed = 'Could not resume feeds',
  HouseholdLeaveFailed = 'Could not leave the household',
  InviteAlreadyJoined = 'You are already in this household',
  InviteAlreadyMember = 'They are already in this household',
  InviteAlreadyUsed = 'That invite has already been used',
  InviteExpired = 'That invite has expired',
  InviteNotFound = 'We could not find that invite',
  InviteJoinFailed = 'Could not join the household',
  InviteRevokeFailed = 'Could not revoke the invite',
  InviteWasRevoked = 'That invite was revoked',
  InviteSendFailed = 'Could not send the invite',
  HouseholdUpdateFailed = 'Could not update the household',
  OwnerRequired = 'A household needs at least one owner',
  MemberRemoveFailed = 'Could not remove the member',
  MemberRoleChangeFailed = 'Could not update the role',
  MedicationRemoveFailed = 'Could not remove the medication',
  ContactSaveFailed = 'Could not save the contact',
  ContactRemoveFailed = 'Could not remove the contact',
  MedicationSaveFailed = 'Could not save the medication',
  MissingPetDetails = 'Missing pet details, go back and try again',
  NameSaveFailed = 'Could not save your name',
  ProfilePhotoUpdateFailed = 'Could not change your profile photo',
  NotificationSettingsUpdateFailed = 'Could not update notification settings',
  OnboardingFailed = 'Could not finish setup',
  PetAddFailed = 'Could not add the pet',
  PetDetailsUpdateFailed = 'Could not update pet details',
  PetPhotoUpdateFailed = 'Could not change the photo',
  PetRemoveFailed = 'Could not remove the pet',
  PhotoAddFailed = 'Could not add the photo',
  PhotoDeleteFailed = 'Could not delete the photo',
  PhotosAddFailed = 'Could not add all of the photos',
  PostDeleteFailed = 'Could not delete the post',
  PostShareFailed = 'Could not share the post',
  PostUpdateFailed = 'Could not update the post',
  PasswordUpdateFailed = 'Could not update your password',
  ResetCodeSendFailed = 'Could not send a reset code',
  CodeResendFailed = 'Could not send a new code',
  SignInFailed = 'Could not sign in',
  SupportEmailUnavailable = 'No email app to contact support from',
  SignOutFailed = 'Failed to sign out',
  SignUpFailed = 'Could not sign up',
  VerificationFailed = 'Could not verify code'
}
