import {
  Asterisk,
  Bell,
  Calendar,
  Camera,
  Check,
  ChevronDown,
  ChevronLeft,
  ChevronRight,
  ChevronUp,
  CircleAlert,
  CircleQuestionMark,
  ClipboardList,
  Clock,
  CreditCard,
  Dot,
  Ellipsis,
  Eye,
  EyeOff,
  FileText,
  Globe,
  Heart,
  Hourglass,
  House,
  Image,
  ImagePlus,
  Info,
  Key,
  Lightbulb,
  List,
  Lock,
  LogOut,
  Mail,
  MessageCircle,
  PawPrint,
  Pencil,
  Plus,
  FlipHorizontal2,
  Settings,
  Share,
  Shield,
  Sparkles,
  Star,
  SunMoon,
  ThumbsUp,
  Trash2,
  User,
  UserPlus,
  Users,
  Utensils,
  X
} from 'lucide-react-native';

export const iconMap = {
  camera: Camera,
  asterisk: Asterisk,
  caretDown: ChevronDown,
  caretUp: ChevronUp,
  caretLeft: ChevronLeft,
  caretRight: ChevronRight,
  dot: Dot,
  eye: Eye,
  eyeOff: EyeOff,
  calendar: Calendar,
  clock: Clock,
  check: Check,
  circleAlert: CircleAlert,
  plus: Plus,
  image: Image,
  imagePlus: ImagePlus,
  utensils: Utensils,
  pencil: Pencil,
  userPlus: UserPlus,
  pawPrint: PawPrint,
  bell: Bell,
  thumbsUp: ThumbsUp,
  heart: Heart,
  comment: MessageCircle,
  ellipsis: Ellipsis,
  close: X,
  trash: Trash2,
  flip: FlipHorizontal2,
  share: Share,
  help: CircleQuestionMark,
  clipboardList: ClipboardList,
  list: List,
  settings: Settings,
  lock: Lock,
  key: Key,
  creditCard: CreditCard,
  sunMoon: SunMoon,
  sparkles: Sparkles,
  house: House,
  users: Users,
  user: User,
  globe: Globe,
  hourglass: Hourglass,
  mail: Mail,
  lightbulb: Lightbulb,
  star: Star,
  info: Info,
  shield: Shield,
  fileText: FileText,
  logOut: LogOut
} as const;

export type IconName = keyof typeof iconMap;
