import { execSync } from 'node:child_process';
import { writeFileSync } from 'node:fs';

import { makeRpcArgsNullable } from './db-types-patch';

const PROJECT_ID = 'dofjrttcyjtzvqyttqdo';
const OUT = 'src/types/database.ts';

// --local reads the database that `supabase db start` built from supabase/migrations.
const source = process.argv.includes('--local') ? '--local' : `--project-id ${PROJECT_ID}`;

const generated = execSync(`bunx supabase gen types typescript ${source} --schema public`, {
  encoding: 'utf8'
});

const HEADER = `/**
 * Generated from supabase/migrations by \`bun run db:types --local\`. Do not edit this file.
 * Change the schema with a migration, then run the command again.
 * Correct an RPC's return shape in src/types/database-overrides.ts.
 */

`;

writeFileSync(OUT, HEADER + makeRpcArgsNullable(generated));
execSync(`bunx prettier --write ${OUT}`);
